### PR TITLE
Fix: LPC IAP correctness

### LINKED ISSUE #1230: LPC812,824,844 do not program
On git head (993c74bef471657981467fe312dfcee45d9da44d) I am unable to program the following devices:
LPC812, LPC824, LPC844

When I run the following debug commands:
```
set print pretty on
set architecture armv6
file bin/LPC824M201HI33_blinky/debug/LPC824M201HI33_blinky.elf
target extended-remote /dev/ttyACM0
monitor tpwr enable
shell sleep 1
monitor swdp_scan
attach 1
set mem inaccessible-by-default off
set {int}0x40048000 = 2
load bin/LPC824M201HI33_blinky/debug/LPC824M201HI33_blinky.elf
set {int}0x40048000 = 2
compare-sections
b main
```
It hangs at the Loading section
```
For help, type "help".
Type "apropos word" to search for commands related to "word".
The target architecture is set to "armv6".
Enabling target power
Target voltage: 3.3V
Available Targets:
No. Att Driver
 1      LPC82x M0+
0x00000164 in main () at projects/LPC824M201HI33_blinky/src/main.cpp:25
25          var = var ^ 0x55;
Loading section .text, size 0x280 lma 0x0
```

Using git bisect from the last good known hash (41719c55) but could not find the commit that is responsible for the break as I got some compilation errors (hashes 0a6621a3, 8eea6110, 9b6d9c47) .

If you have any additional questions or comments, feel free to ask.

### PR DESCRIPTION
**Pull request by dragonmux**
## Detailed description

This PR addresses the breakage that occurred between v1.8.2 and v1.9 in the IAP routines used by the LPC8xx parts, among others. While investigating this it turned out that the `lpc_iap_call` was invoking undefined behaviour and was quite poorly documented.

We've addressed this with a near complete rewrite of the routines affected and adding handling for the LPC8xx parts support to handle their needs around `target_reset()` and entering/exiting Flash mode

## Your checklist for this pull request

* [x] I've read the [Code of Conduct](https://github.com/blackmagic-debug/blackmagic/blob/main/CODE_OF_CONDUCT.md)
* [x] I've read the [guidelines for contributing](https://github.com/blackmagic-debug/blackmagic/blob/main/CONTRIBUTING.md) to this repository
* [x] It builds for hardware native (`make PROBE_HOST=native`)
* [x] It builds as BMDA (`make PROBE_HOST=hosted`)
* [x] I've tested it to the best of my ability
* [x] My commit messages provide a useful short description of what the commits do

## Closing issues

Fixes #1230

### CODE REVIEW

**Review by esden — APPROVED** [review]
LGTM. Will merge after the CI builds finish.
