### ISSUE TITLE
DFU_IFACE_STRING undeclared when building for F4Discovery

### ISSUE THREAD

**Issue by alanbowman** [blackmagic-debug/blackmagic#17]
Building for the F4 Discovery host causes a compile error in the DFU part of the build:

arm-none-eabi-gcc -Wall -Wextra -Wno-pointer-sign -Wno-char-subscripts -Wno-sign-compare -O2 -std=gnu99 -g3 -DBUILDDATE=\"`date +"%Y%m%d"`\" -I. -Iinclude -Iplatforms/f4discovery -DVERSION_SUFFIX=\"`../scripts/setlocalversion`\" -MD -Istm32/include -mcpu=cortex-m3 -mthumb -DSTM32F4 -DF4DISCOVERY -I../libopencm3/include -Iplatforms/stm32   -c -o dfucore.o platforms/stm32/dfucore.c
platforms/stm32/dfucore.c:125:2: error: 'DFU_IFACE_STRING' undeclared here (not in a function)

I have had to modify libopencm3 to use soft float, but no changes other than that.

If I managed to use git bisect properly, then I think the failure was introduced in 14e5e8b0b6dca9dfbcd10021fbe5a8036accb4fb, "Separated clean and dirty bootloader sections"
